### ISSUE TITLE
error running on raspberry pi 4 64-bit python 3.9.2

### ISSUE THREAD

**Issue by johncblacker** [googlesamples/mediapipe#115]

**Comment by johncblacker** [comment]
I'm getting an error trying to run a simple object detection example.  My os is raspberry pi 64-bit, my mediapipe is: 0.8.9.1.  My code errors on statement:
**from mediapipe.tasks import python with error: "moduleNoteFoundError: No module named 'mediapipe.tasks'**
I don't know how to fix the problem.  The example came from the git-hub repo: object_detector.ipynb.  I've lifted the python
code from the notebook and am running using the python mp-objdettest1.py method rather than using colab.  I need some guidance on fixing the problem.

**Comment by PaulTR** [comment]
Hey John. So I believe Raspberry Pi isn't _quite_ supported yet since there's some more under the hood stuff to finish. I'll put out some RPi specific samples though once it is.

If you're specifically trying to run object detection for a project in the meantime, I'd say go for the TensorFlow Task Library. Here's a reference app for that: https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/raspberry_pi

**Comment by johncblacker** [comment]
Sorry to take so long to get back to you.  I appreciate the info you provided and have integrated using the TensorFlow Task Library into my application and have it working; however, I've been trying to figure out what objects the efficientdet_lite0_edgetpu.tflite
has been trained on.  My app is a vehicle detection application and I know that "car" is one of the objects; however, what other classes of ground vehicles can be recognized?  Is there a way I can determine that for a given model using a short python script?  Thank you again.
