### ISSUE TITLE
Modify the mediapipe/examples/pose_landmarker example for Streaming Video

### ISSUE THREAD

**Issue by mcdonasd1212** [googlesamples/mediapipe#162]
Has anyone created a version of the example below using streaming video?  

https://github.com/googlesamples/mediapipe/tree/main/examples/pose_landmarker/python

**Comment by PaulTR** [comment]
So we haven't on the Google side of things, but I just created a feature request discussion board. I'll update our readme to include a link to it/process, but I added this request there: https://github.com/googlesamples/mediapipe/discussions/166

I'll close this out since it'll be better tracked through the discussion board for feature requests.

Thanks for bringing this up!
