### ISSUE TITLE
Python Face Landmark detection uploading own image

### ISSUE THREAD

**Issue by szreik** [googlesamples/mediapipe#197]
Hello, when looking at [MediaPipe_Python_Tasks]_Face_Landmarker.ipynb, the code works perfectly with the sample image. However, when I try to upload my own image, I get a `ValueError: Input image must contain three channel bgr data.`

on line 21: `annotated_image = draw_landmarks_on_image(image.numpy_view(), detection_result)`

How do I go about fixing this? Is there a command I can use to convert the image to three channel bgr data?

Thank you!

**Comment by PaulTR** [comment]
Can you post a bit more detail about what you're running into and if there are any properties that might be specific to the image you're using? Have you tried this with multiple test images?

The main thing is that this line `cv2_imshow(cv2.cvtColor(annotated_image, cv2.COLOR_RGB2BGR))` should handle that conversion for you (it's under step 5 in the main landmarking snippet), but that happens _after_ the step where you're running into the issue. I was able to upload my own custom image in the step above
<img width="562" alt="Screenshot 2023-08-05 at 3 04 14 PM" src="https://github.com/googlesamples/mediapipe/assets/2335087/22bea360-650f-419a-97e2-7255ae7af686">

and get expected results after changing the file name in STEP 3 of that main code block where you're having trouble.

<img width="546" alt="Screenshot 2023-08-05 at 3 08 33 PM" src="https://github.com/googlesamples/mediapipe/assets/2335087/d8d75483-207e-4939-8022-1af022efbe01">


One thing I will point out is that you'll need to run the sample image downloading snippet first because it handles cv2 importing for you, but it looks like you already did that.

Thanks!

**Comment by szreik** [comment]
Thank you for your quick response! The image I was trying to upload is a png image that is a screenshot from a video. I just tried it with a jpeg image I downloaded from Google and got a different error now: 

<img width="938" alt="Screenshot 2023-08-06 at 11 51 55 AM" src="https://github.com/googlesamples/mediapipe/assets/103338909/96989b88-79b7-4aad-a4d2-0d688ef45edc">

I did change the file name in step 3 and also ran the sample image downloading snippet first for both attempted images so I don't know where the problem could be. Any insight would be much appreciated!
