### ISSUE TITLE
How to do custom object trainning using Mediapipe.

### ISSUE THREAD

**Issue by aishwarya123mathpati** [googlesamples/mediapipe#255]
We are having face data, and we wants to train out own model by using transfer learning, currently we are using mediapipe face mesh to generate 478 3d landmarks.

**Comment by PaulTR** [comment]
So face landmarker retraining isn't currently supported right now due to the process of annotating so many points across multiple images, but I'll record the request. If we get enough requests for this, we may be able to add it to the roadmap internally, but I can't make any promises on if/when. Thanks for the feedback!
